name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        cxx_std: [14]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt-get install -y clang
        fi

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=${{ matrix.cxx_std }} ..
        else
          cmake -DCMAKE_CXX_STANDARD=${{ matrix.cxx_std }} ..
        fi

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Test
      run: |
        cd build
        ./minimal_fe_test